export enum TILE_TYPE_ENUM {
    WALL_ROW = 'WALL_ROW',
    WALL_COLUMN = 'WALL_COLUMN',
    WALL_LEFT_TOP = 'WALL_LEFT_TOP',
    WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
    WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
    WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
    CLIFF_LEFT = 'CLIFF_LEFT',
    CLIFF_CENTER = 'CLIFF_CENTER',
    CLIFF_RIGHT = 'CLIFF_RIGHT',
    FLOOR = 'FLOOR',
}

export enum CONTROLLER_ENUM {
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
}

export enum FSM_PARAMS_TYPE_ENUM{
    NUMBER = 'NUMBER',
    TRIGGER = 'TRIGGER',
}

export enum DIRECTION_ENUM{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    RIGHT = 'RIGHT',
    LEFT = 'LEFT',
}

export enum PARAMS_NAME_ENUM{
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
    BLOCKFRONT = 'BLOCKFRONT', //向前撞
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    DIRECTION = 'DIRECTION',
    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH',
    SPIKES_CURRENT_COUNT = 'SPIKES_CURRENT_COUNT',
    SPIKES_TOTAL_COUNT = 'SPIKES_TOTAL_COUNT',
}

export enum EVENT_ENUM {
    NEXT_LEVEL = 'NEXT_LEVEL',
    PLAYER_CTRL = 'PLAYER_CTRL',
    PLAYER_MOVE_END = 'PLAYER_MOVE_END',
    PLAYER_BORN = 'PLAYER_BORN',
    ATTACK_PLAYER = 'ATTACK_PLAYER',
    ATTACK_ENEMY = 'ATTACK_ENEMY',
    DOOR_OPEN = 'DOOR_OPEN',
    SHOW_SMOKE = 'SHOW_SMOKE',
    SCREEN_SHAKE = 'SCREEN_SHAKE',
    RECORD_STEP = 'RECORD_STEP',
    REVOKE_STEP = 'REVOKE_STEP',
    RESTART_LEVEL = 'RESTART_LEVEL',
    OUT_BATTLE = 'OUT_BATTLE',
}

export enum ENTITY_STATE_ENUM{
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
    BLOCKFRONT = 'BLOCKFRONT',
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    BLOCKBACK = 'BLOCKBACK',
    BLOCKRIGHT = 'BLOCKRIGHT',
    BLOCKLEFT = 'BLOCKLEFT',
    BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH',
}

export enum DIRECTION_ODER_ENUM{
    TOP = 0,
    BOTTOM = 1,
    RIGHT = 2,
    LEFT = 3,
}

export enum SHAKE_TYPE_ENUM{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    RIGHT = 'RIGHT',
    LEFT = 'LEFT',
}

export enum ENTITY_TYPE_ENUM{
    PLAYER = 'PLAYER',
    SKELETON_WOODEN = 'SKELETON_WOODEN',
    SKELETON_IRON = 'SKELETON_IRON',
    DOOR = 'DOOR',
    BURST = 'BURST',
    SPIKES_ONE = 'SPIKES_ONE',
    SPIKES_TWO = 'SPIKES_TWO',
    SPIKES_THREE = 'SPIKES_THREE',
    SPIKES_FOUR = 'SPIKES_FOUR',
    SMOKE = 'SMOKE',
}

export enum SPIKES_TYPE_MAP_TOTAL_COUNT_ENUM{
    SPIKES_ONE = 2,
    SPIKES_TWO = 3,
    SPIKES_THREE = 4,
    SPIKES_FOUR = 5,
}

export enum SPIKES_COUNT_ENUM{
    ZERO = 'ZERO',
    ONE = 'ONE',
    TWO = 'TWO',
    THREE = 'THREE',
    FOUR = 'FOUR',
    FIVE = 'FIVE',
}

export enum SPIKES_COUNT_MAP_NUMBER_ENUM{
    ZERO = 0,
    ONE = 1,
    TWO = 2,
    THREE = 3,
    FOUR = 4,
    FIVE = 5,
}

export enum SCENE_ENUM{
    Loading = 'Loading',
    Start = 'Start',
    Battle = 'Battle',
}